{{- range $componentName, $component := .Values.components }}
{{- if ne ($component.enabled | default true) false }}
{{- if $component.ingress }}
{{- if $component.ingress.basicAuth }}
{{- if $component.ingress.basicAuth.enabled }}
{{- if and $component.ingress.basicAuth.username $component.ingress.basicAuth.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.componentFullname" (dict "releaseName" $.Release.Name "componentName" $componentName) }}-auth
  labels:
    {{- include "app.componentLabels" (dict "root" $ "componentName" $componentName) | nindent 4 }}
    {{- with include "app.customLabels" (dict "global" $.Values.global "component" $component) }}
    {{- . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  auth: {{ (htpasswd $component.ingress.basicAuth.username $component.ingress.basicAuth.password) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
